language: go

go:
  - 1.9.1

go_import_path: code.opsmind.com/prometheus/

before_script:
  - cd $TRAVIS_BUILD_DIR/..
  - git clone --depth=50 -b $TRAVIS_BRANCH git@github.com:opsmind/common.git
  - cd common
  - git checkout $TRAVIS_BRANCH
  - go install ./...
  - cd $TRAVIS_BUILD_DIR


script: go test $(go list ./... | grep -v /vendor/)

install:
 - true

deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master
    
